name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: pnpm/action-setup
      - name: Install modules
        run: pnpm install
      - name: Run Test Coverage
        run: cd packages/mosaic-ui && pnpm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action
        with:
          directory: packages/mosaic-ui/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
