name: CI

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Install modules
        run: pnpm install
      - name: Run Lint components
        run: cd packages/mosaic-ui && pnpm run lint
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Install modules
        run: pnpm install
      - name: Run Test Components
        run: cd packages/mosaic-ui && pnpm run test
  PreBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - name: Install modules
        run: pnpm install
      - name: Run Build Components
        run: cd packages/mosaic-ui && pnpm run build
